rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - spec/gemfiles/Gemfile.ar-3.2
  - spec/gemfiles/Gemfile.ar-4.0
  - spec/gemfiles/Gemfile.ar-edge

before_script:
  - mysql -e 'create database rescue_from_duplicate;'

env:
  - POSTGRES=1 POSTGRES_URL=$(curl http://api.postgression.com)
  - MYSQL=1

matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.ar-edge
